### ISSUE TITLE
Weird requirement of searching user

### ISSUE THREAD

**Issue by lo0k0502** [bartchao/donshuBackend#11]
## Routes
`/private/user/searchUser`

## Description
我跟著Swagger的指示傳了query => search=lo
但他給了我400的error:
![截圖 2023-05-19 上午2 56 10](https://github.com/ccudonshi/donshuBackend/assets/79895881/51436096-401f-4704-859c-dfd751b97383)
api key和token都有帶

然後當我也加上json body => { "search": "any" } 之後神奇的通過了
![截圖 2023-05-19 上午2 58 58](https://github.com/ccudonshi/donshuBackend/assets/79895881/9c37c28b-9cee-429e-8e08-84a0062a22e6)
是不是有什麼多的驗證機制？
因為看起來並沒有管我body帶的值是什麼
但有檢查body有沒有search欄位的存在
比如我將body改成 { "asd": "any" } 就重新回傳了上面的錯誤訊息

## Expectation
應該只檢查並使用query裡面的欄位

**Comment by lo0k0502** [comment]
我猜是原本的驗證沒清乾淨？

**Comment by bartchao** [comment]
掛了Validator，但是從body改成query時忘記改validator設定
