### ISSUE TITLE
Query Empty Posts Returns 404 Not Found

### ISSUE THREAD

**Issue by ccudonshi** [bartchao/donshuBackend#14]
## Routes
 - /public/post/query

## Description
我在測試delete post時把isNeed = false, typeId = 7的posts全部刪除了
然後我再用query的api時就會回傳404 Not Found
這會讓app在要切換到該頁面時throw error並導致無法切換至該頁面

## Expectation
若找不到資料可以回傳空陣列

**Comment by lo0k0502** [comment]
這我發的
忘記換帳號哈哈

**Comment by bartchao** [comment]
https://github.com/ccudonshi/donshuBackend/issues/14

**Comment by bartchao** [comment]
If a request is succeed,server will return 204 instead of 404.
