### ISSUE TITLE
Uploads Route Returns 500 Internal Server Error

### ISSUE THREAD

**Issue by ccudonshi** [bartchao/donshuBackend#15]
## Routes
 - /uploads/{upload}

## Description
部分image在讀取時會回傳500 Internal Server Error
像是這個 `user_id = 2a088582-3688-436c-a6bc-d92887d5f0ab` & `username = 顏鈺杰`的user

<img width="1219" alt="截圖 2023-05-24 上午12 49 11" src="https://github.com/ccudonshi/donshuBackend/assets/112961069/e489e02a-ee83-4f0b-960e-f2d11e55c456">

## Expectation
確保/uploads/{upload}能回傳相對應的檔案

**Comment by lo0k0502** [comment]
這也我發的哈哈

**Comment by bartchao** [comment]
remove old buggy code,use built-in `express.static()` instead.
If file requested not found in server,will return 404 instead of 500.
If still received error 500, that would be a real server error.
